version: '3'
services:
  user:
    build: ./service-user
    ports:
      - "3001:3000"
  product:
    build: ./service-product
    ports:
      - "3002:3000"
  gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user
      - product
rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "15672:15672"   # interface web
    - "5672:5672"     # port AMQP
