version: '3'
service-user:
    build: ./service-user
    container_name: service-user
    depends_on:
      - rabbitmq
    ports:
      - "3001:3000"

  service-product:
    build: ./service-product
    container_name: service-product
    depends_on:
      - rabbitmq
    ports:
      - "3002:3000"
  gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user
      - product
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"   # interface web
      - "5672:5672"     # port AMQP
  environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
