global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:4001']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:4002']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:4003']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:4004']
